version: '3.7'

# Network Configuration
networks:
  personal-services:
    driver: bridge

# Volume Configuration
volumes:
  postgresql-data-product:

# Services Configuration
services:
  # Product Service
  # This service runs the .NET Core application container, built from a Dockerfile in the current context.
  product:
    container_name: product
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - 56508:56508
    networks:
    - personal-services
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerDev"

  # Product PostgreSQL Database
  # This service uses the official PostgreSQL 13 image, configured with environment variables for user and password.
  # It includes volume mappings for data persistence and script management.
  product-postgres:
    image: postgres:13
    container_name: product-postgres
    restart: unless-stopped
    # mounts db data to file system so data is not lost when re-creating the container.
    volumes:
      - postgresql-data-product:/var/lib/postgresql/data
      - ./.db:/scripts
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: password
    ports:
      - "28515:5432"
    networks:
      - personal-services