version: '3.7'

# Setting up a network for our containers to talk to each other
networks:
  personal-services:
    driver: bridge

# Creating a place to keep database data safe
volumes:
  postgresql-data-product:

# Describing the containers we want to run
services:
  # Product Service
  # This container runs our main app, made from a Dockerfile.
  product:
    container_name: product
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - 56508:56508
    networks:
    - personal-services
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerDev"

  # Product PostgreSQL Database
  # This container uses a PostgreSQL database to store data.
  # We set it up with a username and password and make sure data is saved even if the container restarts.
  product-postgres:
    image: postgres:13
    container_name: product-postgres
    restart: unless-stopped
    # Saves database data to a special place so we don't lose it when restarting the container.
    volumes:
      - postgresql-data-product:/var/lib/postgresql/data
      - ./.db:/scripts
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: password
    ports:
      - "28515:5432"
    networks:
      - personal-services